### ISSUE TITLE
Output image pixels

### ISSUE THREAD

**Issue by sonal-bansal** [mseitzer/srgan#5]
Hi,
I've trained my SRResnet on DIV2K and during testing I've tried SET14.
Here is my resulting image
![output](https://user-images.githubusercontent.com/33753404/52631192-1fa77480-2ee4-11e9-9563-0098ec5160c2.png)

My image is having this weird green/blue pixels  around sharp and bright regions.Is this because my model isn't working well or do i need to perform further processing on my output?
What do u suggest?

**Comment by mseitzer** [comment]
You should not need any further post-processing on the output. Sorry, I don't know what these artifacts are caused by. Carefully check every part of your implementation for bugs would be my first suggestion.
